services:
  db:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
  app:
    image: stjarnstoft/mydiaryapp
    ports:
      - 80:8080
    environment:
      - MongoDbEntrySettings__ConnectionString=mongodb://db:27017

volumes:
  mongodata:

# services:
#   server:
#     build:
#       context: .
#       target: final
#     ports:
#       - 8080:8080
