name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/mydiaryapp:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mydiaryapp:${{ github.sha }}
  
  deploy_containers:
    runs-on: self-hosted
    needs: build_and_push

    steps:
      - name: Clean up old container
        run: |
          sudo docker rm -f MyDiaryApp
      - name: Put up new container
        run: |
          sudo docker run -d -p 80:8080 --name MyDiaryApp ${{ secrets.DOCKERHUB_USERNAME }}/mydiaryapp:${{ github.sha }}