name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/mydiaryapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mydiaryapp:latest
  
  deploy_containers:
    runs-on: self-hosted

    steps:
      - name: Clean up old containers
        run: |
          sudo docker compose down
      - name: Put up new containers
        run: |
          sudo docker compose up -d
        working-directory: ${{ github.workspace }}