name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/mydiaryapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mydiaryapp:latest
      
      - name: Save compose as an artifact?
        uses: actions/upload-artifact@v2
        with:
          name: compose
          path: ${{ github.workspace }}/compose.yaml
  
  deploy_containers:
    runs-on: self-hosted
    needs: build_and_push

    steps:
      - name: Download compose artifact
        uses: actions/download-artifact@v2
        with:
          name: compose
          path: /tmp
      - name: Clean up old containers
        run: |
          sudo docker rm -f $(sudo docker ps -aq)
      - name: Put up new containers
        run: |
          sudo docker compose --file /tmp/compose.yaml up -d